FROM python:3.12-slim as builder

WORKDIR /app
RUN pip install uv
COPY pyproject.toml uv.lock /app/
RUN uv venv --python 3.12 venv \
    && PATH="/app/venv/bin:$PATH" \
    VIRTUAL_ENV="/app/venv" \
    uv sync --active --no-dev

FROM python:3.12-slim

WORKDIR /app

COPY --from=builder /app/venv /app/venv
COPY . /app

ENV PATH="/app/venv/bin:$PATH"
ENV VIRTUAL_ENV="/app/venv"

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]